# forge create ./src/Marketplace.sol:ResourceMarketplace \
# 	    --rpc-url https://virtual.mainnet.rpc.tenderly.co/fb47656a-9c0a-4215-8df3-f520a29b2548 \
# 	    --verify \
# 	    --verifier-url https://api.tenderly.co/api/v1/verify/3a82b8cf-6f83-4bee-91bc-93c8a2bbb4bb \
# 	    --etherscan-api-key OrjruEdeuEoUt0SBakqsS3vpxr6c-wYD \
# 	    --private-key e62fd5eafc74f599dab28b51ec9718134fe61c35b1b076c07eec832b52d8f547

# forge create ./src/Marketplace.sol:ResourceMarketplace --rpc-url https://virtual.mainnet.rpc.tenderly.co/22c80466-0778-4342-b53f-a550a870dddc --private-key e62fd5eafc74f599dab28b51ec9718134fe61c35b1b076c07eec832b52d8f547               
deploy:
	forge create ./src/Marketplace.sol:ResourceMarketplace --rpc-url https://open-campus-codex-sepolia.drpc.org --private-key 66416396cdc802d43bbbf7236fbf169ca452226288bfa43b6302b77973e17db2 --         

	forge verify-contract 0xaD1F7b657550f8520bd32E0B3817E05430395DE7 --chain-id 656476 --etherscan-api-key OrjruEdeuEoUt0SBakqsS3vpxr6c-wYD  ./src/Marketplace.sol:ResourceMarketplace --rpc-url https://open-campus-codex-sepolia.drpc.org 
#  {
#         network: "opencampus",
#         chainId: 656476,
#         urls: {
#           apiURL: "https://opencampus-codex.blockscout.com/api",
#           browserURL: "https://opencampus-codex.blockscout.com/",
#         },




