import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import { ConnectButton, ThirdwebProvider } from "thirdweb/react";
import { client } from "@/lib/client";
import { Toaster } from "react-hot-toast";
import { Sidebar } from "@/components/sidebar";
import { Breadcrumb } from "@/components/breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider>
          <StoreProvider>
            <div className="flex min-h-screen">
              <Sidebar />
              <div className="flex-grow">
                <div className="absolute top-3 right-3">
                  <div className="flex justify-center mb-20">
                    <ConnectButton
                      client={client}
                      theme={"light"}
                      appMetadata={{
                        name: "Example App",
                        url: "https://example.com",
                      }}
                    />
                  </div>
                </div>
                <main className="p-6">
                  <div className="flex flex-col gap-4">
                    <div>
                      <Breadcrumb />
                    </div>
                    <div>{children}</div>
                  </div>
                </main>
              </div>
            </div>
            <Toaster position="top-center" reverseOrder={false} />
          </StoreProvider>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
